services:
  api:
    image: rajim59/swarmfort-api:latest
    deploy:
      resources:
        limits:
          cpus: "2.00"      
          memory: 1G        
        reservations:
          cpus: "1.00"
          memory: 512M